### ISSUE TITLE
Kind Container Fails to Start

### ISSUE THREAD

**Issue by csviri** [dajudge/kindcontainer#235]
I have the following simple test:

```java
public class KindContainerTest {

    KindContainer<?> KUBE = new KindContainer<>();

    @Test
    void runKindContainer() {
        KUBE.start();
    }

}
```

Kind container fails to start with the following logs:

```
2023-08-16 14:01:23,129 1 o.t.u.ImageNameSubstitutor     [INFO ] Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2023-08-16 14:01:23,750 1 o.t.d.DockerClientProviderStrategy [INFO ] Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2023-08-16 14:01:23,942 1 o.t.d.DockerClientProviderStrategy [INFO ] Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
2023-08-16 14:01:23,943 1 o.t.DockerClientFactory        [INFO ] Docker host IP address is localhost
2023-08-16 14:01:23,956 1 o.t.DockerClientFactory        [INFO ] Connected to docker: 
  Server Version: 24.0.5
  API Version: 1.43
  Operating System: Linux Mint 21.1
  Total Memory: 15920 MB
2023-08-16 14:01:23,996 1 t.t.5.1                        [INFO ] Creating container for image: testcontainers/ryuk:0.5.1
2023-08-16 14:01:24,081 1 t.t.5.1                        [INFO ] Container testcontainers/ryuk:0.5.1 is starting: 094b8d40d5dc1e7e3584878377b67f53cce7ff67a2346db80b8d383cb44ef2cf
2023-08-16 14:01:24,499 1 t.t.5.1                        [INFO ] Container testcontainers/ryuk:0.5.1 started in PT0.536774S
2023-08-16 14:01:24,503 1 o.t.u.RyukResourceReaper       [INFO ] Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
2023-08-16 14:01:24,503 1 o.t.DockerClientFactory        [INFO ] Checking the system...
2023-08-16 14:01:24,504 1 o.t.DockerClientFactory        [INFO ] ✔︎ Docker server version should be at least 1.6.0
2023-08-16 14:01:24,511 1 t.k.2.0                        [INFO ] Creating container for image: kindest/node:v1.26.0
2023-08-16 14:01:24,538 1 t.k.2.0                        [INFO ] Container kindest/node:v1.26.0 is starting: d38e3f13b23cfdb8a78f93ff552ec5a6a03312fdaa727b64ed30b9c930f26011
2023-08-16 14:02:24,851 1 t.k.2.0                        [ERROR] Could not start container
java.lang.IllegalStateException: Container init does not seem to have started.
	at com.dajudge.kindcontainer.KindContainer.waitForProvisioningSignal(KindContainer.java:170)
	at com.dajudge.kindcontainer.KindContainer.containerIsStarting(KindContainer.java:151)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:479)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at com.dajudge.kindcontainer.KindContainer.start(KindContainer.java:343)
	at io.javaoperatorsdk.operator.KindContainerTest.runKindContainer(KindContainerTest.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
2023-08-16 14:02:24,881 1 t.k.2.0                        [ERROR] Log output from the failed container:
INFO: ensuring we can execute mount/umount even with userns-remap
INFO: remounting /sys read-only
INFO: making mounts shared
INFO: detected cgroup v2
INFO: clearing and regenerating /etc/machine-id
Initializing machine ID from random generator.
INFO: faking /sys/class/dmi/id/product_name to be "kind"
INFO: faking /sys/class/dmi/id/product_uuid to be random
INFO: faking /sys/devices/virtual/dmi/id/product_uuid as well
INFO: setting iptables to detected mode: legacy
INFO: Detected IPv4 address: 172.17.0.3
INFO: Detected IPv6 address: 
systemd 249.11-0ubuntu3.6 running in system mode (+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization docker.
Detected architecture x86-64.

Welcome to Ubuntu 22.04.1 LTS!

Queued start job for default target Graphical Interface.
[  OK  ] Created slice slice used to run Kubernetes / Kubelet.
[  OK  ] Created slice Slice /system/modprobe.
[  OK  ] Started Dispatch Password …ts to Console Directory Watch.
[  OK  ] Set up automount Arbitrary…s File System Automount Point.
[  OK  ] Reached target Local Encrypted Volumes.
[  OK  ] Reached target Path Units.
[  OK  ] Reached target Slice Units.
[  OK  ] Reached target Swaps.
[  OK  ] Reached target Local Verity Protected Volumes.
[  OK  ] Listening on Journal Audit Socket.
[  OK  ] Listening on Journal Socket (/dev/log).
[  OK  ] Listening on Journal Socket.
[  OK  ] Reached target Socket Units.
         Mounting Huge Pages File System...
         Mounting Kernel Debug File System...
         Mounting Kernel Trace File System...
         Starting Journal Service...
         Starting Create List of Static Device Nodes...
         Starting Load Kernel Module configfs...
         Starting Load Kernel Module fuse...
         Starting Remount Root and Kernel File Systems...
         Starting Apply Kernel Variables...
[  OK  ] Mounted Huge Pages File System.
[  OK  ] Mounted Kernel Debug File System.
[  OK  ] Mounted Kernel Trace File System.
[  OK  ] Finished Create List of Static Device Nodes.
modprobe@configfs.service: Deactivated successfully.
[  OK  ] Finished Load Kernel Module configfs.
modprobe@fuse.service: Deactivated successfully.
[  OK  ] Finished Load Kernel Module fuse.
[  OK  ] Finished Remount Root and Kernel File Systems.
         Mounting FUSE Control File System...
         Starting Create System Users...
         Starting Record System Boot/Shutdown in UTMP...
[  OK  ] Mounted FUSE Control File System.
[  OK  ] Finished Apply Kernel Variables.
[  OK  ] Finished Create System Users.
[  OK  ] Finished Record System Boot/Shutdown in UTMP.
         Starting Create Static Device Nodes in /dev...
[  OK  ] Started Journal Service.
         Starting Flush Journal to Persistent Storage...
[  OK  ] Finished Flush Journal to Persistent Storage.
[  OK  ] Finished Create Static Device Nodes in /dev.
[  OK  ] Reached target Preparation for Local File Systems.
[  OK  ] Reached target Local File Systems.
[  OK  ] Reached target System Initialization.
[  OK  ] Started Daily Cleanup of Temporary Directories.
[  OK  ] Reached target Basic System.
[  OK  ] Reached target Timer Units.
         Starting containerd container runtime...
[  OK  ] Started containerd container runtime.
[  OK  ] Reached target Multi-User System.
[  OK  ] Reached target Graphical Interface.
         Starting Record Runlevel Change in UTMP...
[  OK  ] Finished Record Runlevel Change in UTMP.


org.testcontainers.containers.ContainerLaunchException: Container startup failed for image kindest/node:v1.26.0

	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at com.dajudge.kindcontainer.KindContainer.start(KindContainer.java:343)
	at io.javaoperatorsdk.operator.KindContainerTest.runKindContainer(KindContainerTest.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
	... 73 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:553)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 74 more
Caused by: java.lang.IllegalStateException: Container init does not seem to have started.
	at com.dajudge.kindcontainer.KindContainer.waitForProvisioningSignal(KindContainer.java:170)
	at com.dajudge.kindcontainer.KindContainer.containerIsStarting(KindContainer.java:151)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:479)
	... 76 more
```

**Comment by tomaszmichalak** [comment]
I have a similar issue while running `./gradlew clean test`:
```
SomeKindTest STANDARD_OUT
    09:26:49.136 [Test worker] INFO  tc.kindest/node:v1.28.0 - Creating container for image: kindest/node:v1.28.0
    09:26:49.171 [Test worker] INFO  tc.kindest/node:v1.28.0 - Container kindest/node:v1.28.0 is starting: eb77d02e84f8502599dbd46aea2d1815853b1e6dcae18c42233f6584db122394
    09:26:49.483 [Test worker] INFO  c.d.kindcontainer.KindContainer - Container internal IP address: 172.17.0.3
    09:26:49.483 [Test worker] INFO  c.d.kindcontainer.KindContainer - Container external IP address: localhost
    09:26:49.483 [Test worker] INFO  c.d.kindcontainer.KindContainer - Executing command: mkdir -p /kindcontainer
    09:26:49.508 [Test worker] INFO  c.d.kindcontainer.TemplateHelpers - Writing container file: /kindcontainer/kubeadm-1.24.0.yaml
    09:26:49.511 [Test worker] INFO  c.d.kindcontainer.KindContainer - Executing command: kubeadm init --skip-phases=preflight --config=/kindcontainer/kubeadm-1.24.0.yaml --skip-token-print --node-name=kind --v=6
    09:27:21.837 [Test worker] INFO  c.d.kindcontainer.TemplateHelpers - Writing container file: /kindcontainer/cni.yaml
    09:27:21.840 [Test worker] INFO  c.d.kindcontainer.KindContainer - Executing command: kubectl apply -f /kindcontainer/cni.yaml
    09:27:22.191 [Test worker] INFO  c.d.kindcontainer.KindContainer - Executing command: kubectl apply -f /kind/manifests/default-storage.yaml
    09:27:22.438 [Test worker] INFO  c.d.kindcontainer.KindContainer - Executing command: kubectl taint node kind node-role.kubernetes.io/control-plane:NoSchedule-
    09:27:22.504 [Test worker] INFO  c.d.k.KubernetesWithKubeletContainer - Waiting for a node to become ready...
    09:27:45.302 [Test worker] INFO  c.d.k.KubernetesWithKubeletContainer - Node ready: kind
    09:27:45.303 [Test worker] INFO  tc.kindest/node:v1.28.0 - Container kindest/node:v1.28.0 started in PT56.166973S

WebhookTest > obeys_namespace_selector() > com.dajudge.kindcontainer.webhook.WebhookTest.initializationError FAILED
    java.lang.ArrayIndexOutOfBoundsException at ContainerVersionHelpers.java:106

WebhookTest > obeys_object_selector() > com.dajudge.kindcontainer.webhook.WebhookTest.initializationError FAILED
    java.lang.ArrayIndexOutOfBoundsException at ContainerVersionHelpers.java:106
```
Any idea?

**Comment by tomaszmichalak** [comment]
Environment: Mac M1.

**Comment by katheris** [comment]
@csviri @tomaszmichalak did either of you get to the bottom of this? I'm seeing the api server failing to start, running on an Intel-based Mac

**Comment by dajudge** [comment]
> I have a similar issue while running `./gradlew clean test`:
> 
> ```
> SomeKindTest STANDARD_OUT
>     09:26:49.136 [Test worker] INFO  tc.kindest/node:v1.28.0 - Creating container for image: kindest/node:v1.28.0
>     09:26:49.171 [Test worker] INFO  tc.kindest/node:v1.28.0 - Container kindest/node:v1.28.0 is starting: eb77d02e84f8502599dbd46aea2d1815853b1e6dcae18c42233f6584db122394
>     09:26:49.483 [Test worker] INFO  c.d.kindcontainer.KindContainer - Container internal IP address: 172.17.0.3
>     09:26:49.483 [Test worker] INFO  c.d.kindcontainer.KindContainer - Container external IP address: localhost
>     09:26:49.483 [Test worker] INFO  c.d.kindcontainer.KindContainer - Executing command: mkdir -p /kindcontainer
>     09:26:49.508 [Test worker] INFO  c.d.kindcontainer.TemplateHelpers - Writing container file: /kindcontainer/kubeadm-1.24.0.yaml
>     09:26:49.511 [Test worker] INFO  c.d.kindcontainer.KindContainer - Executing command: kubeadm init --skip-phases=preflight --config=/kindcontainer/kubeadm-1.24.0.yaml --skip-token-print --node-name=kind --v=6
>     09:27:21.837 [Test worker] INFO  c.d.kindcontainer.TemplateHelpers - Writing container file: /kindcontainer/cni.yaml
>     09:27:21.840 [Test worker] INFO  c.d.kindcontainer.KindContainer - Executing command: kubectl apply -f /kindcontainer/cni.yaml
>     09:27:22.191 [Test worker] INFO  c.d.kindcontainer.KindContainer - Executing command: kubectl apply -f /kind/manifests/default-storage.yaml
>     09:27:22.438 [Test worker] INFO  c.d.kindcontainer.KindContainer - Executing command: kubectl taint node kind node-role.kubernetes.io/control-plane:NoSchedule-
>     09:27:22.504 [Test worker] INFO  c.d.k.KubernetesWithKubeletContainer - Waiting for a node to become ready...
>     09:27:45.302 [Test worker] INFO  c.d.k.KubernetesWithKubeletContainer - Node ready: kind
>     09:27:45.303 [Test worker] INFO  tc.kindest/node:v1.28.0 - Container kindest/node:v1.28.0 started in PT56.166973S
> 
> WebhookTest > obeys_namespace_selector() > com.dajudge.kindcontainer.webhook.WebhookTest.initializationError FAILED
>     java.lang.ArrayIndexOutOfBoundsException at ContainerVersionHelpers.java:106
> 
> WebhookTest > obeys_object_selector() > com.dajudge.kindcontainer.webhook.WebhookTest.initializationError FAILED
>     java.lang.ArrayIndexOutOfBoundsException at ContainerVersionHelpers.java:106
> ```
> 
> Any idea?

@tomaszmichalak we fixed an issue along those lines recently - any chance you can give this a rerun?

**Comment by dajudge** [comment]
> @csviri @tomaszmichalak did either of you get to the bottom of this? I'm seeing the api server failing to start, running on an Intel-based Mac

Ad hoc this sounds like a different issue - could you maybe open a separate issue and provide a reproducer? 👍

**Comment by katheris** [comment]
> Ad hoc this sounds like a different issue - could you maybe open a separate issue and provide a reproducer? 👍

Strangely at some point this just stopped being a problem and has been fine since, not sure if there was something still starting up in my container environment or what, but haven't been able to reproduce since

**Comment by cmoulliard** [comment]
In order to better investigate such a problem, users should provide more detail such as:
- OS and version
- Container engine and version: podman vs docker
- Rootless or rootful
- Kind image version
and more logging messages are needed to got the error from kubelet or container to understand what failed

**Comment by dajudge** [comment]
Thanks for reporting this.

The original failure dates back to 2023 and has not been reproducible with current Kindcontainer versions. Current CI also starts the supported `KindContainer` versions successfully.

I’m closing this issue as stale. If the problem occurs again with a current Kindcontainer release, please open a new issue including the Kindcontainer version, Docker version, operating system, a minimal reproducer, and the complete container logs.
